FROM adoptopenjdk/openjdk11:latest
WORKDIR /
ADD target/demo-0.0.1-SNAPSHOT-spring-boot.jar demo-0.0.1-SNAPSHOT-spring-boot.jar
EXPOSE 8080
CMD ["java","-jar","demo-0.0.1-SNAPSHOT-spring-boot.jar"]





